language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
script:
  - rustup target add thumbv7em-none-eabihf

  # Check with no_std target to make sure it really works
  - cargo build --target thumbv7em-none-eabihf --manifest-path core/Cargo.toml

  # Test using a full std crate
  - cargo test --manifest-path bbqtest/Cargo.toml -- --nocapture
  - cargo test --release --manifest-path bbqtest/Cargo.toml -- --nocapture
