# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

parameters:
  rust-version: stable

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - template: ci/azure-install-rust.yml

# - script: |
# echo "hello, world!"
#   displayName: 'Run a multi-line script'
