[package]
name = "bbqtest"
version = "0.1.0"
authors = ["James Munns <james.munns@ferrous-systems.com>"]
edition = "2018"

[dependencies.bbqueue]
path = "../core"

[dev-dependencies]
rand = "0.6"

[features]
travisci = []
default = []
