[package]
name = "bbqueue"
version = "0.0.1"
description = "A (WIP) SPSC, lockless, no_std, thread safe, queue, based on BipBuffers"
repository = "https://github.com/jamesmunns/bbqueue"
authors = ["James Munns <james.munns@ferrous-systems.com>"]
edition = "2018"
readme = "../README.md"

categories = ["lock-free", "no-std", "heapless"]
license = "MIT OR Apache-2.0"

[dependencies]
generic-array = "0.12"

